name: Push

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo - Build
        run: echo "Build step"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo - Test
        run: echo "Test step"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Echo - Dev
        run: echo "TODO - Deploy to Dev"

  deploy-uat:
    runs-on: ubuntu-latest
    needs: test
    environment: uat
    steps:
      - name: Echo - UAT
        run: echo "TODO - Deploy to UAT"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test
    environment: prod
    steps:
      - name: Echo - Prod
        run: echo "TODO - Deploy to Prod"
