name: Deploy

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Echo job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Echo job 3
        run: echo "This is job 3"
