name: Push

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo - Build
        run: echo "Build step"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo - Test
        run: echo "Test step"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Echo - DEV
        run: echo "TODO - Deploy to DEV"

      - name: echo SHA
        run: echo "SHA $GITHUB_SHA"

      # - name: Upload Last Deployment SHA
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: last_deploy_sha
      #     path: last_deploy_sha.txt

  deploy-uat:
    runs-on: ubuntu-latest
    needs: test
    environment: uat
    steps:
      - name: Echo - UAT
        run: echo "TODO - Deploy to UAT"

      - name: Get sha of latest deployment in main branch
        id: latest-deployment-sha
        uses: vrnithinkumar/latest-deployment-sha@v1.0.0
        with:
          repo_owner: vrnithinkumar
          repo_name: latest-deployment-sha
          environment: production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print latest deployment sha
        id: output
        run: echo "${{ steps.latest-deployment-sha.outputs.sha }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test
    environment: prod
    steps:
      - name: Echo - Prod
        run: echo "TODO - Deploy to Prod"
