name: Merge

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo - Validate
        run: echo "Validate step"

  tag:
    runs-on: ubuntu-latest
    environment: tag
    needs: validate
    steps:
      - name: Echo - Tag
        run: echo "Tag step - ${{ github.event.commits.id }}"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ github.event.commits.id }}',
              sha: context.sha
            })
