name: Push

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo - Validate
        run: echo "Validate step"

      - name: Test
        run: echo "github.event.after - ${{ github.event.after }}"
      - name: Test2
        run: echo "github.event.base_ref - ${{ github.event.base_ref }}"
      - name: Test2
        run: echo "github.event.before - ${{ github.event.before }}"
