name: Tag

on:
  push:
    tags:
      - v**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo - Validate
        run: echo "Validate step"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: validate
    environment: dev
    steps:
      - name: Echo - DEV
        run: echo "TODO - Deploy to DEV"

      - name: echo SHA
        run: echo "SHA $GITHUB_SHA"

  deploy-uat:
    runs-on: ubuntu-latest
    needs: validate
    environment: uat
    steps:
      - name: Echo - UAT
        run: echo "TODO - Deploy to UAT"

      - name: Get sha of latest deployment in main branch
        id: latest-deployment-sha
        uses: vrnithinkumar/latest-deployment-sha@v1.0.0
        with:
          repo_owner: vrnithinkumar
          repo_name: latest-deployment-sha
          environment: uat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print latest deployment sha
        id: output
        run: echo "${{ steps.latest-deployment-sha.outputs.sha }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: validate
    environment: prod
    steps:
      - name: Echo - Prod
        run: echo "TODO - Deploy to Prod"

      - name: Get sha of latest deployment in main branch
        id: latest-deployment-sha
        uses: vrnithinkumar/latest-deployment-sha@v1.0.0
        with:
          repo_owner: vrnithinkumar
          repo_name: latest-deployment-sha
          environment: uat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print latest deployment sha
        id: output
        run: echo "${{ steps.latest-deployment-sha.outputs.sha }}"
