name: Post Merge/Tag

on:
  workflow_run:
    workflows: [Merge, Tag]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - run: echo "${{ github.event.workflow_run.name }}"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: echo "${{ github.event.workflow_run.name }}"
